name: smartclass
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.10.1
  # file_picker: ^8.0.3
  open_filex: ^4.4.0
  file_selector: ^0.9.0
  sign_in_with_apple: ^6.0.0
  url_launcher: ^6.2.4
  dio: ^5.4.2
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  fl_chart: ^0.69.0
  intl: ^0.19.0
  http: ^1.5.0
  curved_navigation_bar: ^1.0.1
  # syncfusion_flutter_pdfviewer: ^25.2.5
  pdfx: ^2.9.2
  pdf: ^3.10.4
  printing: ^5.12.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^7.0.0
  flutter_markdown: ^0.7.2
  image_picker: ^1.2.1
  flutter_markdown_selectionarea: ^0.6.17+1
  # speech_to_text: ^6.5.1
  # image_picker: ^1.0.7
  lottie: ^3.1.2
  smooth_page_indicator: ^1.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.8

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/icon1.png"
  adaptive_icon_background: "assets/images/icon-bg.png"
  # adaptive_icon_foreground: "assets/images/icon.png"
 
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/